In [8]:
library("dplyr")

## Inputs: 

1. Set of nodes *Z*
2. Ordering of the nodes
3. Upper bound on the number of parents (for each node) *u*
4. Database *D* of m cases

In [10]:
N_tensor <- function(D, i, V.i, pi.i){
    result <- D %>% count(D[,pi.i], name='j_counts')
    result <- result$j_counts
        for (k in V.i){
            mask <- D[, i]==k
            k_count <- D[mask,] %>% count(D[mask,pi.i])
            result<-data.frame(result, k_count[,length(k_count)])
            colnames(result)[length(colnames(result))]<- k
        }
        result[is.na(result)] <- 0
    names(result)[1] <- 'j_counts'
    names(result)[2:(length(V.i)+1)] <- V.i
    return(result)
}

g <- function(V.i, r.i, N.tensor){
    N.ij <- N.tensor$j_counts
    q.i <- length(N.ij) # number of unique combinations of the parents realizations
    result <- 1
    for (j in 1:q.i) {
        a <- 1
        for (k in V.i){a <- a*factorial(N.tensor[j,as.character(k)])}
        result <- result*a*factorial(r.i-1)/factorial(N.ij[j]+r.i-1)
    }
    #print(paste('func',result))
    return(result)
}


k2 <- function(Z, u, D){
    V <- unname(sapply(D, unique)) #it's a matrix
    r <- unname(sapply(D, n_distinct)) #it's a vector
    parents <- list()
    for (i in 1:length(Z)){
        cat('\n iteration', i)
        pi.i <- NULL 
        Nijk <- N_tensor(D, Z[i], V[,i], pi.i)
        P_old <- g(V[,i],r[i], Nijk)
        proceed <- TRUE
        while (proceed & (length(pi.i)<u & i>1)){
            pred.i <- setdiff(Z[1:i-1], pi.i)
            #print(paste('pi', pi.i))
            #print(paste('pred', pred.i))
            P <- NULL
            for (node in pred.i){
                new_set <- union(pi.i, node)
                Nijk <- N_tensor(D, Z[i], V[,i], new_set)
                P<- c(P, g(V[,i], r[i], Nijk))
            }
            cat('\n POLD IS ', P_old)
            cat('\n p is ', P, 'n')
            if (max(P) > P_old){
                print("ok")
                max.indx <- which.max(P)
                P_old <- P[max.indx]
                pi.i <- union(pi.i, pred.i[max.indx])
            }
            else {proceed = FALSE}
        }
        append(parents, list(pi.i))
    } 
    return(parents)
}

In [17]:
x1 <- c(1,1,0,1,0,0,1,0,1,0)
x2 <- c(0,1,0,1,0,1,1,0,1,0)
x3<- c(0,1,1,1,0,1,1,0,1,0)

D <- data.frame(x1, x2, x3)

print(D)

   x1 x2 x3
1   1  0  0
2   1  1  1
3   0  0  1
4   1  1  1
5   0  0  0
6   0  1  1
7   1  1  1
8   0  0  0
9   1  1  1
10  0  0  0

In [5]:
papitos <- k2(c(1,2,3), u=3, D)
papitos

 iteration 1

ERROR: Error: Column `D[, pi.i]` is of unsupported class data.frame

In [63]:
N_tensor <- function(D, i, V.i, pi.i){
    result <- D%>% group_by_at(names(D)[pi.i]) %>% mutate(j_counts=n())
    
        for (k in V.i){
            result.k <- D %>% filter(D[,i]==k) %>% group_by_at(names(D)[pi.i]) %>% mutate(k=n())
            colnames(result.k)[length(colnames(result.k))]<- k
            result<-left_join(result, result.k, by=names(D)[pi.i])
            print(result)
        }
        result[is.na(result)] <- 0
    #result<-result %>% group_by_at(names(result)[pi.i]) %>% filter(row_number() == 1)
    #print(result)
    return(result)
}

g <- function(V.i, r.i, N.tensor){
    N.ij <- N.tensor$j_counts
    print(N.ij)
    q.i <- length(N.ij) # number of unique combinations of the parents realizations
    result <- 1
    for (j in 1:q.i) {
        a <- 1
        for (k in V.i){a <- a*factorial(N.tensor[j,as.character(k)])}
        result <- result*a*factorial(r.i-1)/factorial(N.ij[j]+r.i-1)
    }
    return(result)
}


k2 <- function(Z, u, D){
    V <- unname(sapply(D, unique)) #it's a matrix
    r <- unname(sapply(D, n_distinct)) #it's a vector
    parents <- list()
    for (i in 1:length(Z)){
        cat('\n iteration', i)
        pi.i <- NULL 
        Nijk <- N_tensor(D, Z[i], V[,i], pi.i)
        P_old <- g(V[,i],r[i], Nijk)
        proceed <- TRUE
        while (proceed & (length(pi.i)<u & i>1)){
            pred.i <- setdiff(Z[1:i-1], pi.i)
            P <- NULL
            for (node in pred.i){
                new_set <- union(pi.i, node)
                Nijk <- N_tensor(D, Z[i], V[,i], new_set)
                P<- c(P, g(V[,i], r[i], Nijk))
            }
            P<-unlist(P)
            print(paste("Pold:", P_old))
            print(paste("P:", P))
            if (max(P) > P_old){
                max.indx <- which.max(P)
                P_old <- P[max.indx]
                pi.i <- union(pi.i, pred.i[max.indx])
            }
            else {proceed = FALSE}
        }
        append(parents, list(pi.i))
    } 
    return(parents)
}

In [64]:
k2(c(1,2,3), u=3, D)

 iteration 1# A tibble: 50 × 8
    x1.x  x2.x  x3.x j_counts  x1.y  x2.y  x3.y   `1`
   <dbl> <dbl> <dbl>    <int> <dbl> <dbl> <dbl> <int>
 1     1     0     0       10     1     0     0     5
 2     1     0     0       10     1     1     1     5
 3     1     0     0       10     1     1     1     5
 4     1     0     0       10     1     1     1     5
 5     1     0     0       10     1     1     1     5
 6     1     1     1       10     1     0     0     5
 7     1     1     1       10     1     1     1     5
 8     1     1     1       10     1     1     1     5
 9     1     1     1       10     1     1     1     5
10     1     1     1       10     1     1     1     5
# … with 40 more rows
# A tibble: 250 × 12
    x1.x  x2.x  x3.x j_counts  x1.y  x2.y  x3.y   `1`    x1    x2    x3   `0`
   <dbl> <dbl> <dbl>    <int> <dbl> <dbl> <dbl> <int> <dbl> <dbl> <dbl> <int>
 1     1     0     0       10     1     0     0     5     0     0     1     5
 2     1     0     0       10     1     0     0     5     0     0     0     5
 3     1     0     0       10     1     0     0     5     0     1     1     5
 4     1     0     0       10     1     0     0     5     0     0     0     5
 5     1     0     0       10     1     0     0     5     0     0     0     5
 6     1     0     0       10     1     1     1     5     0     0     1     5
 7     1     0     0       10     1     1     1     5     0     0     0     5
 8     1     0     0       10     1     1     1     5     0     1     1     5
 9     1     0     0       10     1     1     1     5     0     0     0     5
10     1     0     0       10     1     1     1     5     0     0     0     5
# … with 240 more rows
  [1] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 [26] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 [51] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 [76] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[101] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[126] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[151] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[176] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[201] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[226] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10

 iteration 2# A tibble: 50 × 8
    x1.x  x2.x  x3.x j_counts  x1.y  x2.y  x3.y   `0`
   <dbl> <dbl> <dbl>    <int> <dbl> <dbl> <dbl> <int>
 1     1     0     0       10     1     0     0     5
 2     1     0     0       10     0     0     1     5
 3     1     0     0       10     0     0     0     5
 4     1     0     0       10     0     0     0     5
 5     1     0     0       10     0     0     0     5
 6     1     1     1       10     1     0     0     5
 7     1     1     1       10     0     0     1     5
 8     1     1     1       10     0     0     0     5
 9     1     1     1       10     0     0     0     5
10     1     1     1       10     0     0     0     5
# … with 40 more rows
# A tibble: 250 × 12
    x1.x  x2.x  x3.x j_counts  x1.y  x2.y  x3.y   `0`    x1    x2    x3   `1`
   <dbl> <dbl> <dbl>    <int> <dbl> <dbl> <dbl> <int> <dbl> <dbl> <dbl> <int>
 1     1     0     0       10     1     0     0     5     1     1     1     5
 2     1     0     0       10     1     0     0     5     1     1     1     5
 3     1     0     0       10     1     0     0     5     0     1     1     5
 4     1     0     0       10     1     0     0     5     1     1     1     5
 5     1     0     0       10     1     0     0     5     1     1     1     5
 6     1     0     0       10     0     0     1     5     1     1     1     5
 7     1     0     0       10     0     0     1     5     1     1     1     5
 8     1     0     0       10     0     0     1     5     0     1     1     5
 9     1     0     0       10     0     0     1     5     1     1     1     5
10     1     0     0       10     0     0     1     5     1     1     1     5
# … with 240 more rows
  [1] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 [26] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 [51] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 [76] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[101] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[126] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[151] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[176] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[201] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[226] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
# A tibble: 25 × 7
# Groups:   x1 [2]
      x1  x2.x  x3.x j_counts  x2.y  x3.y   `0`
   <dbl> <dbl> <dbl>    <int> <dbl> <dbl> <int>
 1     1     0     0        5     0     0     1
 2     1     1     1        5     0     0     1
 3     0     0     1        5     0     1     4
 4     0     0     1        5     0     0     4
 5     0     0     1        5     0     0     4
 6     0     0     1        5     0     0     4
 7     1     1     1        5     0     0     1
 8     0     0     0        5     0     1     4
 9     0     0     0        5     0     0     4
10     0     0     0        5     0     0     4
# … with 15 more rows
# A tibble: 40 × 10
# Groups:   x1 [2]
      x1  x2.x  x3.x j_counts  x2.y  x3.y   `0`    x2    x3   `1`
   <dbl> <dbl> <dbl>    <int> <dbl> <dbl> <int> <dbl> <dbl> <int>
 1     1     0     0        5     0     0     1     1     1     4
 2     1     0     0        5     0     0     1     1     1     4
 3     1     0     0        5     0     0     1     1     1     4
 4     1     0     0        5     0     0     1     1     1     4
 5     1     1     1        5     0     0     1     1     1     4
 6     1     1     1        5     0     0     1     1     1     4
 7     1     1     1        5     0     0     1     1     1     4
 8     1     1     1        5     0     0     1     1     1     4
 9     0     0     1        5     0     1     4     1     1     1
10     0     0     1        5     0     0     4     1     1     1
# … with 30 more rows
 [1] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[39] 5 5
[1] "Pold: 0"
[1] "P: 8.22526333996995e-60"
[1] "Pold: 8.22526333996995e-60"
[1] "P: "

Warning message in max(P):
“nessun argomento non-mancante al massimo; si restituisce -Inf”

 iteration 3# A tibble: 40 × 8
    x1.x  x2.x  x3.x j_counts  x1.y  x2.y  x3.y   `0`
   <dbl> <dbl> <dbl>    <int> <dbl> <dbl> <dbl> <int>
 1     1     0     0       10     1     0     0     4
 2     1     0     0       10     0     0     0     4
 3     1     0     0       10     0     0     0     4
 4     1     0     0       10     0     0     0     4
 5     1     1     1       10     1     0     0     4
 6     1     1     1       10     0     0     0     4
 7     1     1     1       10     0     0     0     4
 8     1     1     1       10     0     0     0     4
 9     0     0     1       10     1     0     0     4
10     0     0     1       10     0     0     0     4
# … with 30 more rows
# A tibble: 240 × 12
    x1.x  x2.x  x3.x j_counts  x1.y  x2.y  x3.y   `0`    x1    x2    x3   `1`
   <dbl> <dbl> <dbl>    <int> <dbl> <dbl> <dbl> <int> <dbl> <dbl> <dbl> <int>
 1     1     0     0       10     1     0     0     4     1     1     1     6
 2     1     0     0       10     1     0     0     4     0     0     1     6
 3     1     0     0       10     1     0     0     4     1     1     1     6
 4     1     0     0       10     1     0     0     4     0     1     1     6
 5     1     0     0       10     1     0     0     4     1     1     1     6
 6     1     0     0       10     1     0     0     4     1     1     1     6
 7     1     0     0       10     0     0     0     4     1     1     1     6
 8     1     0     0       10     0     0     0     4     0     0     1     6
 9     1     0     0       10     0     0     0     4     1     1     1     6
10     1     0     0       10     0     0     0     4     0     1     1     6
# … with 230 more rows
  [1] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 [26] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 [51] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 [76] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[101] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[126] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[151] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[176] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[201] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
[226] 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
# A tibble: 20 × 7
# Groups:   x1 [2]
      x1  x2.x  x3.x j_counts  x2.y  x3.y   `0`
   <dbl> <dbl> <dbl>    <int> <dbl> <dbl> <int>
 1     1     0     0        5     0     0     1
 2     1     1     1        5     0     0     1
 3     0     0     1        5     0     0     3
 4     0     0     1        5     0     0     3
 5     0     0     1        5     0     0     3
 6     1     1     1        5     0     0     1
 7     0     0     0        5     0     0     3
 8     0     0     0        5     0     0     3
 9     0     0     0        5     0     0     3
10     0     1     1        5     0     0     3
11     0     1     1        5     0     0     3
12     0     1     1        5     0     0     3
13     1     1     1        5     0     0     1
14     0     0     0        5     0     0     3
15     0     0     0        5     0     0     3
16     0     0     0        5     0     0     3
17     1     1     1        5     0     0     1
18     0     0     0        5     0     0     3
19     0     0     0        5     0     0     3
20     0     0     0        5     0     0     3
# A tibble: 50 × 10
# Groups:   x1 [2]
      x1  x2.x  x3.x j_counts  x2.y  x3.y   `0`    x2    x3   `1`
   <dbl> <dbl> <dbl>    <int> <dbl> <dbl> <int> <dbl> <dbl> <int>
 1     1     0     0        5     0     0     1     1     1     4
 2     1     0     0        5     0     0     1     1     1     4
 3     1     0     0        5     0     0     1     1     1     4
 4     1     0     0        5     0     0     1     1     1     4
 5     1     1     1        5     0     0     1     1     1     4
 6     1     1     1        5     0     0     1     1     1     4
 7     1     1     1        5     0     0     1     1     1     4
 8     1     1     1        5     0     0     1     1     1     4
 9     0     0     1        5     0     0     3     0     1     2
10     0     0     1        5     0     0     3     1     1     2
# … with 40 more rows
 [1] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[39] 5 5 5 5 5 5 5 5 5 5 5 5
# A tibble: 25 × 7
# Groups:   x2 [2]
    x1.x    x2  x3.x j_counts  x1.y  x3.y   `0`
   <dbl> <dbl> <dbl>    <int> <dbl> <dbl> <int>
 1     1     0     0        5     1     0     4
 2     1     0     0        5     0     0     4
 3     1     0     0        5     0     0     4
 4     1     0     0        5     0     0     4
 5     1     1     1        5    NA    NA    NA
 6     0     0     1        5     1     0     4
 7     0     0     1        5     0     0     4
 8     0     0     1        5     0     0     4
 9     0     0     1        5     0     0     4
10     1     1     1        5    NA    NA    NA
# … with 15 more rows
# A tibble: 45 × 10
# Groups:   x2 [2]
    x1.x    x2  x3.x j_counts  x1.y  x3.y   `0`    x1    x3   `1`
   <dbl> <dbl> <dbl>    <int> <dbl> <dbl> <int> <dbl> <dbl> <int>
 1     1     0     0        5     1     0     4     0     1     1
 2     1     0     0        5     0     0     4     0     1     1
 3     1     0     0        5     0     0     4     0     1     1
 4     1     0     0        5     0     0     4     0     1     1
 5     1     1     1        5    NA    NA    NA     1     1     5
 6     1     1     1        5    NA    NA    NA     1     1     5
 7     1     1     1        5    NA    NA    NA     0     1     5
 8     1     1     1        5    NA    NA    NA     1     1     5
 9     1     1     1        5    NA    NA    NA     1     1     5
10     0     0     1        5     1     0     4     0     1     1
# … with 35 more rows
 [1] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[39] 5 5 5 5 5 5 5
[1] "Pold: 0"
[1] "P: 1.29729096693782e-83" "P: 1.00877345589085e-49"
# A tibble: 18 × 6
# Groups:   x2, x1 [4]
      x1    x2  x3.x j_counts  x3.y   `0`
   <dbl> <dbl> <dbl>    <int> <dbl> <int>
 1     1     0     0        1     0     1
 2     1     1     1        4    NA    NA
 3     0     0     1        4     0     3
 4     0     0     1        4     0     3
 5     0     0     1        4     0     3
 6     1     1     1        4    NA    NA
 7     0     0     0        4     0     3
 8     0     0     0        4     0     3
 9     0     0     0        4     0     3
10     0     1     1        1    NA    NA
11     1     1     1        4    NA    NA
12     0     0     0        4     0     3
13     0     0     0        4     0     3
14     0     0     0        4     0     3
15     1     1     1        4    NA    NA
16     0     0     0        4     0     3
17     0     0     0        4     0     3
18     0     0     0        4     0     3
# A tibble: 30 × 8
# Groups:   x2, x1 [4]
      x1    x2  x3.x j_counts  x3.y   `0`    x3   `1`
   <dbl> <dbl> <dbl>    <int> <dbl> <int> <dbl> <int>
 1     1     0     0        1     0     1    NA    NA
 2     1     1     1        4    NA    NA     1     4
 3     1     1     1        4    NA    NA     1     4
 4     1     1     1        4    NA    NA     1     4
 5     1     1     1        4    NA    NA     1     4
 6     0     0     1        4     0     3     1     1
 7     0     0     1        4     0     3     1     1
 8     0     0     1        4     0     3     1     1
 9     1     1     1        4    NA    NA     1     4
10     1     1     1        4    NA    NA     1     4
# … with 20 more rows
 [1] 1 4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 4 4 4 4 4 4 4 4 4 4 4 4 4 4
[1] "Pold: 1.00877345589085e-49"
[1] "P: 4e-28"
[1] "Pold: 4e-28"
[1] "P: "

Warning message in max(P):
“nessun argomento non-mancante al massimo; si restituisce -Inf”

list()

In [65]:
?merge

In [9]:
?dplyr::mutate

In [50]:
?dplyr::full_join

In [62]:
pi.i<-c(2,3)
names(D)[pi.i]

[1] "x2" "x3"